on: push

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"

      - name: checkout
        uses: actions/checkout@v2

      - name: gofmt
        run: test -z $(gofmt -l ./ | tee /dev/stderr)

      - name: go test
        run: go test ./...
